"""Tests for mirach/cli.py — env helper round-trips and lang subcommand.

These tests do NOT import sounddevice and do NOT touch the real mirach.env.
All env I/O uses a tmp_path fixture.  systemd and voice downloads are mocked.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from mirach.cli import _voice_lang, main, read_env, set_env_vars
from mirach.langpack import LANGUAGE_PACKS, pack_for

# ── read_env / set_env_vars ────────────────────────────────────────────────────


def test_read_env_nonexistent_returns_empty(tmp_path):
    assert read_env(tmp_path / "missing.env") == {}


def test_read_env_basic(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("MIRACH_LOCALE=es\nMIRACH_WHISPER_MODEL=medium\n")
    env = read_env(f)
    assert env["MIRACH_LOCALE"] == "es"
    assert env["MIRACH_WHISPER_MODEL"] == "medium"


def test_read_env_ignores_comments_and_blanks(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("# a comment\n\nMIRACH_LOCALE=en\n# another\n")
    env = read_env(f)
    assert list(env.keys()) == ["MIRACH_LOCALE"]


def test_read_env_splits_on_first_equals(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("MIRACH_VOICE_URL=https://host/path?a=1&b=2\n")
    env = read_env(f)
    assert env["MIRACH_VOICE_URL"] == "https://host/path?a=1&b=2"


def test_set_env_vars_creates_file_with_header(tmp_path):
    f = tmp_path / "new.env"
    set_env_vars({"MIRACH_LOCALE": "es"}, f)
    text = f.read_text()
    assert "MIRACH_LOCALE=es" in text
    assert text.startswith("#")  # has header comment


def test_set_env_vars_upsert_existing_key(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("# comment\nMIRACH_LOCALE=en\nMIRACH_HOTKEY=Alt+Z\n")
    set_env_vars({"MIRACH_LOCALE": "es"}, f)
    env = read_env(f)
    assert env["MIRACH_LOCALE"] == "es"
    assert env["MIRACH_HOTKEY"] == "Alt+Z"


def test_set_env_vars_appends_new_key(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("MIRACH_LOCALE=en\n")
    set_env_vars({"MIRACH_VOICE": "es_MX-ald-medium.onnx"}, f)
    env = read_env(f)
    assert env["MIRACH_LOCALE"] == "en"
    assert env["MIRACH_VOICE"] == "es_MX-ald-medium.onnx"


def test_set_env_vars_preserves_comments(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("# Generated by install.py\n# See mirach.env.example\n\nMIRACH_LOCALE=en\n")
    set_env_vars({"MIRACH_LOCALE": "es"}, f)
    text = f.read_text()
    assert "# Generated by install.py" in text
    assert "# See mirach.env.example" in text


def test_set_env_vars_idempotent(tmp_path):
    f = tmp_path / "mirach.env"
    f.write_text("MIRACH_LOCALE=es\n")
    set_env_vars({"MIRACH_LOCALE": "es"}, f)
    set_env_vars({"MIRACH_LOCALE": "es"}, f)
    lines = [ln for ln in f.read_text().splitlines() if ln.startswith("MIRACH_LOCALE=")]
    assert len(lines) == 1


def test_round_trip(tmp_path):
    f = tmp_path / "mirach.env"
    data = {"MIRACH_LOCALE": "es", "MIRACH_WHISPER_MODEL": "medium", "MIRACH_HOTKEY": "Alt+Z"}
    set_env_vars(data, f)
    assert read_env(f) == data


# ── _voice_lang heuristic ──────────────────────────────────────────────────────


def test_voice_lang_spanish():
    assert _voice_lang("es_MX-ald-medium.onnx") == "es"


def test_voice_lang_english():
    assert _voice_lang("en_US-lessac-low.onnx") == "en"


def test_voice_lang_unknown_returns_empty():
    assert _voice_lang("custom-voice.onnx") == ""


def test_voice_lang_no_extension():
    assert _voice_lang("es_MX-ald-medium") == "es"


# ── cmd_lang integration ───────────────────────────────────────────────────────


def _run_lang(tmp_env: Path, code: str, extra: list[str] | None = None, monkeypatch=None) -> int:
    """Run main(['lang', code]) pointing at a temp env file, with mocked systemd/download."""
    argv = ["--env-file", str(tmp_env), "lang", code] + (extra or [])
    return main(argv)


@pytest.fixture()
def mocked_cli(monkeypatch):
    """Patch out systemd and voice download so lang tests are side-effect free."""
    monkeypatch.setattr("mirach.cli._systemd_unit_active", lambda: False)
    monkeypatch.setattr("mirach.cli._download_voice", lambda *a, **kw: None)


def test_lang_es_writes_three_keys(tmp_path, mocked_cli):
    f = tmp_path / "mirach.env"
    pack = pack_for("es")
    rc = main(["--env-file", str(f), "lang", "es", "--yes"])
    assert rc == 0
    env = read_env(f)
    assert env["MIRACH_LOCALE"] == pack["locale"]
    assert env["MIRACH_WHISPER_MODEL"] == pack["whisper_model"]
    assert env["MIRACH_WHISPER_LANG"] == pack["whisper_lang"]


def test_lang_en_writes_three_keys(tmp_path, mocked_cli):
    f = tmp_path / "mirach.env"
    pack = pack_for("en")
    rc = main(["--env-file", str(f), "lang", "en", "--yes"])
    assert rc == 0
    env = read_env(f)
    assert env["MIRACH_LOCALE"] == pack["locale"]
    assert env["MIRACH_WHISPER_MODEL"] == pack["whisper_model"]
    assert env["MIRACH_WHISPER_LANG"] == pack["whisper_lang"]


def test_lang_invalid_code_returns_nonzero(tmp_path, mocked_cli):
    f = tmp_path / "mirach.env"
    rc = main(["--env-file", str(f), "lang", "fr"])
    assert rc != 0


def test_lang_with_yes_changes_voice_on_mismatch(tmp_path, monkeypatch):
    """--yes auto-accepts the voice change when voice lang != target lang."""
    downloaded: list[str] = []
    monkeypatch.setattr("mirach.cli._systemd_unit_active", lambda: False)
    monkeypatch.setattr(
        "mirach.cli._download_voice",
        lambda name, url, d: downloaded.append(name),
    )

    f = tmp_path / "mirach.env"
    # Pre-set an English voice so there's a mismatch when switching to es
    set_env_vars({"MIRACH_VOICE": "en_US-lessac-low.onnx"}, f)

    rc = main(["--env-file", str(f), "lang", "es", "--yes"])
    assert rc == 0

    env = read_env(f)
    assert env["MIRACH_VOICE"] == pack_for("es")["voice"]
    assert len(downloaded) == 1


def test_lang_voice_mismatch_detection():
    """Voice lang heuristic correctly identifies mismatch."""
    assert _voice_lang("en_US-lessac-low.onnx") != "es"
    assert _voice_lang("es_MX-ald-medium.onnx") != "en"


def test_lang_no_change_when_voice_already_matches(tmp_path, monkeypatch):
    """No voice download when voice already matches target language."""
    downloaded: list[str] = []
    monkeypatch.setattr("mirach.cli._systemd_unit_active", lambda: False)
    monkeypatch.setattr(
        "mirach.cli._download_voice",
        lambda name, url, d: downloaded.append(name),
    )

    f = tmp_path / "mirach.env"
    # Pre-set a Spanish voice — no mismatch when switching to es
    set_env_vars({"MIRACH_VOICE": "es_MX-ald-medium.onnx"}, f)

    rc = main(["--env-file", str(f), "lang", "es", "--yes"])
    assert rc == 0
    assert downloaded == []


def test_lang_all_packs_have_required_keys():
    """Regression: every language pack provides the 3 keys the CLI writes."""
    for code in LANGUAGE_PACKS:
        pack = pack_for(code)
        assert "locale" in pack
        assert "whisper_model" in pack
        assert "whisper_lang" in pack
